//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposit
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int value { get; set; }
        public Nullable<int> version { get; set; }
    
        public virtual client client { get; set; }
    }
}
