//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int product_id { get; set; }
        public string productname { get; set; }
        public int productprice { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
